services:
  - type: web
    name: turnex-api
    env: node
    rootDir: server
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm run start:render
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
