services:
  - type: web
    name: turnex-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm ci
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ACCESS_TOKEN_TTL
        value: 15m
      - key: REFRESH_TOKEN_TTL
        value: 7d
      - key: FRONTEND_ORIGIN
        value: https://euge-90.github.io
      - key: CORS_ALLOWED_ORIGINS
        value: https://euge-90.github.io,https://euge-90.github.io/turnex
      # Opcionales:
      # - key: DATABASE_URL
      #   fromSecret: POSTGRES_URL
      # - key: JWT_SECRET
      #   fromSecret: JWT_SECRET
