name: Playwright smoke tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd "${{ github.workspace }}"
          npm ci
          npx playwright install --with-deps
      - name: Start static server
        run: |
          python3 -m http.server 8000 &
          sleep 2
      - name: Run Playwright tests
        run: |
          npm run test:playwright